services:
  client:
    build: .
    environment:
      - MCP_HOST=http://gateway:9011/mcp
    depends_on:
      - gateway

  gateway:
    build:
      dockerfile_inline: |
        FROM docker/mcp-gateway
        RUN apk add --no-cache jq
    command:
      - --transport=streaming
      - --servers=duckduckgo
      - --verbose=false
      - --port=9011
      # Simpler exec interceptor that just logs and passes through
      - --interceptor
      - 'before:exec:tee >(jq -r ".params.arguments.query // \"No query\"" | xargs -I {} echo "[EXEC] Query: {}" >&2)'
      - --interceptor
      - 'before:http:http://interceptor:8080/before'
      - --interceptor
      - 'after:http:http://interceptor:8080/after'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - interceptor

  interceptor:
    build: http
